PLUGIN_NAME=		blocky
PLUGIN_VERSION=		1.0
PLUGIN_COMMENT=		DNS proxy and ad-blocker
PLUGIN_MAINTAINER=	pyarmak@gmail.com
PLUGIN_DEPENDS=		blocky
PLUGIN_WWW=		https://github.com/0xERR0R/blocky

.include "../../Mk/plugins.mk"
