[start]
command:/usr/local/opnsense/scripts/OPNsense/Blocky/setup.sh; /usr/local/etc/rc.d/blocky_opn start
parameters:
type:script
message:Starting blocky service

[stop]
command:/usr/local/etc/rc.d/blocky_opn stop
parameters:
type:script
message:Stopping blocky service

[restart]
command:/usr/local/opnsense/scripts/OPNsense/Blocky/setup.sh; /usr/local/etc/rc.d/blocky_opn restart
parameters:
type:script
message:Restarting blocky service

[status]
command:/usr/local/etc/rc.d/blocky_opn status
errors:no
parameters:
type:script_output
message:Requesting blocky status

[validate]
command:/usr/local/opnsense/scripts/OPNsense/Blocky/validate.sh
parameters:
type:script_output
message:Validating blocky configuration
