[start]
command:/usr/local/opnsense/scripts/OPNsense/Blocky/prepare.sh; /usr/local/etc/rc.d/blocky_opn start
parameters:
type:script
message:Starting blocky service

[stop]
command:/usr/local/etc/rc.d/blocky_opn stop
parameters:
type:script
message:Stopping blocky service

[restart]
command:/usr/local/opnsense/scripts/OPNsense/Blocky/prepare.sh; /usr/local/etc/rc.d/blocky_opn restart
parameters:
type:script
message:Restarting blocky service

[status]
command:/usr/local/etc/rc.d/blocky_opn status
errors:no
parameters:
type:script_output
message:Requesting blocky status

[validate]
command:/usr/local/opnsense/scripts/OPNsense/Blocky/validate.sh
parameters:
type:script_output
message:Validating blocky configuration

[blockingstatus]
command:/usr/local/opnsense/scripts/OPNsense/Blocky/api.py status
parameters:
type:script_output
message:Requesting blocky blocking status

[blockingenable]
command:/usr/local/opnsense/scripts/OPNsense/Blocky/api.py enable
parameters:
type:script_output
message:Enabling blocky blocking

[blockingdisable]
command:/usr/local/opnsense/scripts/OPNsense/Blocky/api.py disable
parameters:%s %s
type:script_output
message:Disabling blocky blocking

[listsrefresh]
command:/usr/local/opnsense/scripts/OPNsense/Blocky/api.py refresh
parameters:
type:script_output
message:Refreshing blocky lists
description:Refresh blocky block and allow lists

[cacheflush]
command:/usr/local/opnsense/scripts/OPNsense/Blocky/api.py flush
parameters:
type:script_output
message:Flushing blocky cache

[stats]
command:/usr/local/opnsense/scripts/OPNsense/Blocky/api.py stats
parameters:
type:script_output
message:Requesting blocky statistics

[query]
command:/usr/local/opnsense/scripts/OPNsense/Blocky/api.py query
parameters:%s %s
type:script_output
message:Looking up %s with blocky

[querylogfiles]
command:/usr/local/opnsense/scripts/OPNsense/Blocky/querylog.py files
parameters:
type:script_output
message:Listing blocky query log files

[querylogsearch]
command:/usr/local/opnsense/scripts/OPNsense/Blocky/querylog.py search
parameters:%s %s %s %s
type:script_output
message:Searching the blocky query log
